name: Doubletap
version: "${version}"
main: doubletap.boopninja.doubletap.Doubletap
api-version: 1.16
load: STARTUP
authors: [ mbround18 ]
description: Tap into a PaperMC servers capabilites
website: doubletap.boop.ninja
