name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:jdk11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: gradle build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            build/libs/*.jar
            README.md
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download latest release
        uses: actions/download-artifact@v2
        with:
          name: release
      # Update tag and pre-release
      # - Update (force-push) tag to the commit that is used in the workflow.
      # - Upload artifacts defined by the user.
      - uses: eine/tip@master
        with:
          tag: latest-snapshot
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/libs/*.jar
            README.md